# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from typing import Any
import json
import os
import struct

CHUNK_SIZE = 64 * 1024 * 1024
def _vp() -> Any:
    ...

KDF_ITERATIONS = 480000
VERIFY_FILE = 'v.dat'
MANIFEST_FILE = 'manifest.dat'
def derive_key(license_key: str, salt: bytes) -> bytes:
    ...

def encrypt_bytes(data: bytes, dst_path: str, license_key: str) -> None:
    ...

def encrypt_file(src_path: str, dst_path: str, license_key: str) -> None:
    ...

def decrypt_file(enc_path: str, dst_path: str, license_key: str) -> None:
    ...

def decrypt_to_bytes(enc_path: str, license_key: str) -> bytes:
    ...

def verify_license(enc_dir: str, license_key: str) -> bool:
    ...

def read_manifest(enc_dir: str, license_key: str) -> dict[str, str]:
    ...

def decrypt_engine(enc_dir: str, tmp_dir: str, license_key: str) -> str:
    ...

def decrypt_engine_to_memory(enc_dir: str, license_key: str) -> dict[str, bytes]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import os
import struct
import cryptography
import cryptography.hazmat
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.kdf
import cryptography.hazmat.primitives.kdf.pbkdf2
import cryptography.hazmat.primitives.hashes
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.aead
import base64
import ntpath