# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
import hashlib
import json
import os
import platform
import struct
import subprocess
import sys
import time

_SRV = [104, 116, 116, 112, 115, 58, 47, 47, 108, 117, 109, 105, 110, 97, 45, 97, 105, 45, 100, 101, 109, 111, 46, 118, 101, 114, 99, 101, 108, 46, 97, 112, 112]
PRODUCT_ID = 'nano-imageedit'
OFFLINE_GRACE_DAYS = 30
HEARTBEAT_INTERVAL_DAYS = 14
def _run_cmd(cmd: str) -> str:
    ...

def _get_machine_id() -> str:
    ...

def _machine_label() -> str:
    ...

def _dpapi_entropy() -> bytes:
    ...

def _save_lock(data: dict) -> None:
    ...

def _load_lock() -> dict | None:
    ...

def _clear_lock() -> None:
    ...

def is_activated() -> bool:
    ...

def get_master_key() -> str | None:
    ...

def _derive_transport_key(machine_id: str) -> bytes:
    ...

def _decrypt_master_key(encrypted_hex: str, machine_id: str) -> str:
    ...

def _api_call(endpoint: str, payload: dict, timeout: int) -> tuple[int, dict]:
    ...

def activate_online(license_key: str, force_takeover: bool) -> dict:
    ...

def verify_online() -> dict:
    ...

def deactivate_online() -> dict:
    ...

def activate_or_verify() -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import hashlib
import json
import os
import platform
import struct
import subprocess
import sys
import time
import urllib
import urllib.request
import urllib.error
import ntpath
import key_vault
import cryptography
import cryptography.hazmat
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.aead